# Generated by Django 6.0.2 on 2026-03-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_unit',
            new_name='preparation_time_unit',
        ),
    ]
